objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Import</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Contract Ops Review</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/L2O_Stage_Metric__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Stage Metrics</relationshipLabel>
        <relationshipName>Stage_Metrics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>L2O_From_Stage__c</fullName>
        <label>From Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2O_Opportunity_Stage</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2O_To_Stage__c</fullName>
        <label>To Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2O_Opportunity_Stage</valueSetName>
        </valueSet>
    </fields>
    <label>Stage Metric</label>
    <nameField>
        <displayFormat>SM-{00000}</displayFormat>
        <label>Stage Metric Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage Metrics</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <description>This record type used for Stage Metrics adaptation for Agreements</description>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/L2O_StageMetricTriggerHandler_Test.cls
/**
* Company : Teladoc.
* @description : Test Class for L2O_StageMetricTriggerHandler apex
* ************************************************************************************************************************************
* History : 
* @date 05/23/2024
* @author Sachin Pawar
*/

@istest
public class L2O_StageMetricTriggerHandler_Test {
    /**
* @name  testcatchException()
* @description Tests L2O_StageMetricTriggerHandler class catch block
* @params  none
*/
    @istest
    public static void testcatchException() {
        Test.startTest();
        L2O_StageMetricTriggerHandler helper = new L2O_StageMetricTriggerHandler();
        helper.beforeInsert();
        helper.beforeUpdate();
        Test.stopTest();       
    }
    /**
* @name  testsetGUID()
* @description Tests Stage metric record creation on agreement stage Update
* @params  none
*/
    @istest
    public static void testAgreementStageMetrics() {
        list<Account> accList= L2O_DataFactoryTest.createAccount(true,1);
        Apttus__APTS_Agreement__c tempAgreement = new Apttus__APTS_Agreement__c(Name = 'Test', Apttus__Account__c = accList[0].Id);
        Test.startTest();
        tempAgreement.Apttus__Status_Category__c = 'In Authoring';
        insert tempAgreement;
        Test.stopTest();
        tempAgreement.Apttus__Status__c = 'Author Contract';
        Update tempAgreement;
        tempAgreement.Apttus__Status__c = 'Language Approval';
        Update tempAgreement;
        List<L2O_Stage_Metric__c> lstStageMetrics = [SELECT Id,Name,Agreement__c, L2O_To_Stage__c, L2O_From_Stage__c FROM L2O_Stage_Metric__c ];
        System.assertEquals(2,lstStageMetrics.Size(),'Creation Test Successful');
    }
    
}