objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity from which this Contract was created.</description>
        <inlineHelpText>The Opportunity from which this Contract was created.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalQuoted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select this option to automatically generate a renewal quote on renewal opportunities.</description>
        <inlineHelpText>Select this option to automatically generate a renewal quote on renewal opportunities.</inlineHelpText>
        <label>Renewal Quoted</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2O_Subtype__c</fullName>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Sale</fullName>
                </value>
                <value>
                    <fullName>Hunting License</fullName>
                </value>
                <value>
                    <fullName>Pilot</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Pilot to Paid Conversion</fullName>
                </value>
                <value>
                    <fullName>Attrition / Expiry</fullName>
                </value>
                <value>
                    <fullName>Pilot Extension</fullName>
                </value>
                <value>
                    <fullName>Contract Path Change</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                    <isActive>false</isActive>
                    <label>Expansion</label>
                </value>
                <value>
                    <fullName>Expansion / Add-On</fullName>
                    <isActive>false</isActive>
                    <label>Expansion / Add-On</label>
                </value>
                <value>
                    <fullName>Initial Sale - Direct</fullName>
                    <isActive>false</isActive>
                    <label>Initial Sale - Direct</label>
                </value>
                <value>
                    <fullName>New Population</fullName>
                    <isActive>false</isActive>
                    <label>New Population</label>
                </value>
                <value>
                    <fullName>Recontracting</fullName>
                    <isActive>false</isActive>
                    <label>Recontracting</label>
                </value>
                <value>
                    <fullName>Renewal + Expansion</fullName>
                    <isActive>false</isActive>
                    <label>Renewal + Expansion</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <description>Approval Status of the Quote</description>
        <inlineHelpText>Approval Status of the Quote.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L2O_Disable_Renewal_Co_Term__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Renewal Co-Term</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>End date for subscriptions in this group.</description>
        <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
        <inlineHelpText>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Indicates the type of quote.</description>
        <inlineHelpText>Indicates the type of quote.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote</fullName>
                    <default>true</default>
                    <label>Quote</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Re-Quote</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/L2O_QuoteTriggerHandler_Test.cls
/**
* Company : PwC.
* @description : Test Class for L2O_QuoteTriggerHandler apex
* ************************************************************************************************************************************
* History : 
* @date 25/02/2022
* @author Harshita Paliwal
*/
@isTest
public class L2O_QuoteTriggerHandler_Test extends L2O_DataFactoryTest{
    
    /**
    * @name  testSetup 
    * @description To create setup records for test class.
    * @params  none
    **/
    @testSetup
    static void testSetup() {
       
        List<Account> accountList= L2O_DataFactoryTest.createAccount(true,1);  
        List<Opportunity> oppList = L2O_DataFactoryTest.createOpportunity(true,accountList); 
        List<Contact> conList =  L2O_DataFactoryTest.createContact(true,accountList); 
        L2O_DataFactoryTest.createContactRoles(true,oppList,conList[0].id); 
        List<User> lstSystemAdmin = L2O_DataFactoryTest.createUsers(true,1,'System Administrator');
        List<User> lstClientManager = L2O_DataFactoryTest.createUsers(true,1,'Client Success');
         L2O_DataFactoryTest.createContactRoles(true,oppList,conList[0].id);    
         List<SBQQ__Quote__c> quoteList =  L2O_DataFactoryTest.createQuote(true,oppList);    
         L2O_DataFactoryTest.createContract(oppList,QuoteList,accountList[0].id); 
        
        //Make Client Manager as Manager of System Admin
        lstSystemAdmin[0].ManagerId = lstClientManager[0].Id;
        User updateAdminUser = lstSystemAdmin[0];
        update updateAdminUser;
        
    }
    
    /**
    * @name  testQuoteDefaultValues
    * @description To test the Quote default fields with automated values.
    * @params  none
    **/
    @isTest static void testQuoteDefaultValues() {
        Test.startTest();
        List<Account> account = [SELECT Id FROM Account WHERE Name != null LIMIT 1];
        List<Opportunity> opportunity =[SELECT Id,stageName FROM Opportunity WHERE Name != null LIMIT 1];
        
        Integer months = 12;
        Date startDate = Date.today();
        
        SBQQ__Quote__c quote = new SBQQ__Quote__c(SBQQ__Opportunity2__c  = opportunity[0].Id, SBQQ__Account__c = account[0].Id,
                                                  SBQQ__StartDate__c = startDate,SBQQ__SubscriptionTerm__c =months,SBQQ__Status__c = 'Draft');  
        
        insert quote;
        
        //Update the Quote with Approved Status
        quote.SBQQ__Status__c = 'Approved';  
        update quote;
        
        SBQQ__Quote__c quoteTest = [SELECT SBQQ__EndDate__c,SBQQ__Primary__c FROM SBQQ__Quote__c WHERE Name != null AND Id=:quote.Id];     
        //Date testDate = startDate.addMonths(months) - 1;
        //checking assertion for EndDate which is starteDate+SubscriptionTerm
        //System.assertEquals(testDate, quoteTest.SBQQ__EndDate__c,'Quote End Date is not set.');
        //checking assertion for Quote is Primary when it is Approved Status.
        System.assertEquals(true, quoteTest.SBQQ__Primary__c,'Quote Primary is False'); 
        Test.stopTest();     
        
    }
    
    /**
    * @name  testApprovalStatusToQuoteStatus
    * @description To test the Approval Status to Quote Status mapping updates
    * @params  none
    **/
    @isTest static void testApprovalStatusToQuoteStatus() {
        Test.startTest();
        List<Account> account = [SELECT Id FROM Account WHERE Name != null LIMIT 1];
        List<Opportunity> opportunity =[SELECT Id FROM Opportunity WHERE Name != null LIMIT 1];
        
        Integer months = 12;
        Date startDate = Date.today();
        
        SBQQ__Quote__c quote = new SBQQ__Quote__c(SBQQ__Opportunity2__c  = opportunity[0].Id, SBQQ__Account__c = account[0].Id,
                                                  SBQQ__StartDate__c = startDate,SBQQ__SubscriptionTerm__c =months);  
        
        insert quote;
        
        SBQQ__Quote__c quoteTest = [SELECT SBQQ__Status__c FROM SBQQ__Quote__c WHERE id=:quote.id LIMIT 1];
        
        //Initial Quote Status = Draft
        System.assertEquals('Draft', quoteTest.SBQQ__Status__c,'Quote Status is not Draft');
        
        //Updating the Approval Status = Pending        
        quoteTest.ApprovalStatus__c = 'Pending';  
        update quoteTest;
        //SBQQ__Quote__c quoteTest1 = [SELECT SBQQ__Status__c FROM SBQQ__Quote__c WHERE id=:quote.id LIMIT 1];
        //checking assertion for Quote Status when Approval Status = Pending.
        //System.assertEquals('In Review', quoteTest1.SBQQ__Status__c,'Quote Status did not update to Pending'); 

		//Updating the Approval Status = Approved        
        quoteTest.ApprovalStatus__c = 'Approved';  
        update quoteTest;
        //SBQQ__Quote__c quoteTest2 = [SELECT SBQQ__Status__c FROM SBQQ__Quote__c WHERE id=:quote.id LIMIT 1];
        //checking assertion for Quote Status when Approval Status = Approved.
        //System.assertEquals('Approved', quoteTest2.SBQQ__Status__c,'Quote Status did not update to Approved'); 
        
        Test.stopTest();     
        
    }
    
    /**
    * @name  testQuoteShare
    * @description To test the Quote Share records.
    * @params  none
    **/
    @isTest static void testQuoteShare() {
        Test.startTest();
        List<Account> account = [SELECT Id FROM Account WHERE Name != null LIMIT 1];
        List<Opportunity> opportunity =[SELECT Id FROM Opportunity WHERE Name != null LIMIT 1];
        
        User systemAdmin =[SELECT Id,lastname,ManagerId FROM User 
                            WHERE lastname LIKE 'TestDataFactory%' AND ManagerId != null AND Profile.Name = 'System Administrator' LIMIT 1];
        
    
       
        System.runAs(systemAdmin){
            Integer months = 12;
            Date startDate = Date.today();
            
            SBQQ__Quote__c quote = new SBQQ__Quote__c(SBQQ__Opportunity2__c  = opportunity[0].Id, SBQQ__Account__c = account[0].Id,
                                                      SBQQ__StartDate__c = startDate,SBQQ__SubscriptionTerm__c =months);  
            
            insert quote;
            System.assertEquals(12, quote.SBQQ__SubscriptionTerm__c,'Quote is not updated');
            
          /*  List<SBQQ__Quote__Share> lstQuoteShare = [SELECT Id,UserOrGroupId, ParentId, AccessLevel FROM SBQQ__Quote__Share 
                                                      WHERE ParentId =: quote.Id
                                                      AND UserOrGroupId =: systemAdmin.ManagerId LIMIT 50];
            
           
            //To assert the Owner's Manager has Edit access to the Quote.
        	System.assertEquals('Edit', lstQuoteShare[0].AccessLevel,'Quote is not shared with Owners Manager');
            System.assertEquals(clientManager.Id, lstQuoteShare[0].UserOrGroupId,'Quote is not shared with Owners Manager');*/
        }
        
        Test.stopTest();   
        
    }
    /**
    * @name  testQuoteShare
    * @description To test the Quote Share records.
    * @params  none
    **/
    @isTest static void testQuoteStatusChange() {
        Test.startTest();
        
        Integer months = 12;
        Date startDate = Date.today();
        List<Account> account = [SELECT Id FROM Account WHERE Name != null LIMIT 1];
        List<Opportunity> opportunity =[SELECT Id FROM Opportunity WHERE Name != null LIMIT 1];
        SBQQ__Quote__c quote = new SBQQ__Quote__c(SBQQ__Opportunity2__c  = opportunity[0].Id, SBQQ__Account__c = account[0].Id,
                                                  SBQQ__StartDate__c = startDate,SBQQ__SubscriptionTerm__c = months,SBQQ__Status__c= 'Draft',SBQQ__Primary__c = true); 
        insert quote;
        quote.SBQQ__Status__c = 'In Review';
        update quote;
        system.assert(quote.SBQQ__Status__c == 'In Review', 'the status changed');
        Test.stopTest();
    }
    /**
    * @name  testQuoteDisableRenewaCoTerm
    * @description To test If field "Disable Renewal Co-Term" is checked on the Quote, then the Renewal Quote's End Date would be blank.
    * @params  none
    **/
    @isTest static void testQuoteDisableRenewaCoTerm() {
         Test.startTest();
        //fetch Contract
        Contract contractRec = [SELECT Id,contractNumber,SBQQ__Opportunity__r.L2O_Subtype__c,SBQQ__Opportunity__r.OwnerId,SBQQ__Opportunity__c  FROM Contract WHERE ContractTerm = 12 LIMIT 1];
        // update contract to generate Renewal Quote
	   contractRec.SBQQ__RenewalQuoted__c = true;
        update contractRec;
        // Fetch Renewal Quote
        SBQQ__Quote__c quote = [SELECT Id,L2O_Disable_Renewal_Co_Term__c,SBQQ__EndDate__c FROM SBQQ__Quote__c WHERE SBQQ__Type__c = 'Renewal' LIMIT 1];
        // update Quote
        quote.L2O_Disable_Renewal_Co_Term__c = true;
         update quote;
        // Fetch the updated Renewal Quote
       SBQQ__Quote__c updtedquote = [SELECT iD, SBQQ__EndDate__c FROM SBQQ__Quote__c WHERE Id=: quote.Id LIMIT 1];
        system.assert(updtedquote.SBQQ__EndDate__c == null, 'End Date updated to blank');
        Test.stopTest();
    }

    /**
	* @name  testcatchException()
	* @description Tests L2O_QuoteTriggerHandler class catch block
	*/
    @istest
    public static void testcatchException() {
        Test.startTest();
        L2O_QuoteTriggerHandler helper = new L2O_QuoteTriggerHandler();
        helper.beforeInsert();
        helper.afterInsert();
        helper.beforeUpdate();
        helper.afterUpdate();
        Test.stopTest();
        SDF_LGR_Log__c errorLog = [SELECT Name, Id, Class__c, Message__c, Reference__c FROM SDF_LGR_Log__c WHERE Class__c = 'L2O_QuoteTriggerHandler' LIMIT 1];
        System.assertEquals('L2O_QuoteTriggerHandler',errorLog.Class__c,'Handler Test Successful');
    }
}