objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>L2O_Sub_Type_Detail__c</fullName>
        <label>Sub-Type Detail</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add-On Membership</fullName>
                </value>
                <value>
                    <fullName>Price Increase</fullName>
                </value>
                <value>
                    <fullName>Upgrade/Upsell</fullName>
                </value>
                <value>
                    <fullName>Price Increase + Upgrade/Upsell</fullName>
                </value>
                <value>
                    <fullName>Price Decrease</fullName>
                </value>
                <value>
                    <fullName>Reporting Purposes Only</fullName>
                </value>
                <value>
                    <fullName>Delayed Launch</fullName>
                </value>
                <value>
                    <fullName>Did Not Launch</fullName>
                </value>
                <value>
                    <fullName>Multi-Year Subscription Increase</fullName>
                </value>
                <value>
                    <fullName>Multi-Year Visit Fee Increase</fullName>
                </value>
                <value>
                    <fullName>Visit Fee Increase</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>L2O_Unit_Sell_Price__c</fullName>
        <label>Unit Sell Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/SBQQ__ProductOption__c.object
<CustomObject>
    <customHelpPage>SBQQ__ProductOptionHelp</customHelpPage>
    <description>Option for a configurable product.</description>
    <label>Product Option</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Options</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__ProductOption__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product option that generated this line (if any).</description>
        <inlineHelpText>Product option that generated this line (if any).</inlineHelpText>
        <label>Product Option</label>
        <referenceTo>SBQQ__ProductOption__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/L2O_GenerateOrder_Controller_Test.cls
@isTest
public class L2O_GenerateOrder_Controller_Test {
    
    public static Id pricebookId = Test.getStandardPricebookId();
    @isTest
    Private static void testGenerateOrder(){
        List<Account> accountList= APTS_TestDataUtility_Test.createAccount(true,1);
        Product2 parentProduct=new Product2();
        Id quoteId;
        Id oppId;
        List<Product2> childproducts=new List<Product2>();
        List<Opportunity> oppList = APTS_TestDataUtility_Test.createOpportunity(true,accountList);
        List<Contact> conList =  APTS_TestDataUtility_Test.createContact(true,accountList); 
        APTS_TestDataUtility_Test.createContactRoles(true,oppList,conList[0].id);
        List<Product2> testproducts=APTS_TestDataUtility_Test.createtestproducts();
        List<SBQQ__Quote__c> quotelist=APTS_TestDataUtility_Test.createQuote(true,oppList);
        for(SBQQ__Quote__c quoterec:quotelist)
        {
            quoteId=quoterec.Id; 
        }
        for(Product2 parprod:testproducts)
        {
            if(parprod.Name=='Mental Health Care (US)')
            {
                parentProduct=parprod;   
            }
            else
            {
                childproducts.add(parprod);   
            }
        }
        for(Opportunity opprec:oppList)
        {
            oppId=opprec.Id;  
        }
        List<SBQQ__ProductOption__c> testproductoptions=APTS_TestDataUtility_Test.createproductoptions(parentProduct,childproducts);
        List<SBQQ__QuoteLine__c> testQuoteLines=APTS_TestDataUtility_Test.createquotelines(quoteId,parentProduct.Id,testproductoptions);
        List<SBQQ__Quote__c> quotesToupdate = New List<SBQQ__Quote__c>();
        for(SBQQ__Quote__c quoteRecord:quotelist)
        {
            quoteRecord.SBQQ__Status__c = 'Accepted';
            quotesToupdate.add(quoteRecord);
        }
        update quotesToupdate;
        List<PricebookEntry> pricebookEntryList = new List<PricebookEntry>();
        for(Product2 objProd : testproducts)
        {
            PricebookEntry pbe1 = new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = objProd.Id,
                UnitPrice = 1020,
                IsActive = true
            );
            pricebookEntryList.add(pbe1);
        }
        insert pricebookEntryList;
    
        Map<Id, Id> mapProdPbe = new Map<Id, Id>();
        for(PricebookEntry objPBE : pricebookEntryList)
        {
            mapProdPbe.put(objPBE.Product2Id, objPBE.Id);
        }

        for(Opportunity objOpp : oppList)
        {
            List<OpportunityLineItem> oppLineitems = New List<OpportunityLineItem>();
            for(SBQQ__QuoteLine__c quoteLine:testQuoteLines){
                OpportunityLineItem oppItem = New OpportunityLineItem();
                oppItem.SBQQ__QuoteLine__c =  quoteLine.Id;
                oppItem.OpportunityId = objOpp.Id;
                oppItem.L2O_Unit_Sell_Price__c = 20;
                oppItem.Quantity = 2;
                oppItem.TotalPrice = 40;
                oppItem.Product2Id = quoteLine.SBQQ__Product__c;
                oppItem.PricebookEntryId = mapProdPbe.get(quoteLine.SBQQ__Product__c);
                oppLineitems.add(oppItem);
            }
            insert oppLineitems;
        }

        oppList[0].StageName = 'Closed Won';
        oppList[0].L2O_Sub_Type_Detail__c = 'Reporting Purposes Only';
        update oppList;
        Contract contractList = L2O_DataFactoryTest.createContract(oppList,quotesToupdate,accountList[0].Id);
        
        Test.startTest();
        L2O_GenerateOrder_Controller.getContracts(oppList[0].Id);
        Test.stopTest(); 
        System.assertNotEquals(null, testQuoteLines, 'Records found successfully');
    }    
    
}