objects/L2O_Stage_Metric__c.object
<CustomObject>
    <fields>
        <fullName>Business_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Business Hours</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>L2O_Current_Stage_Date__c</fullName>
        <formula>CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>To Stage Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>L2O_From_Stage_Date__c</fullName>
        <label>From Stage Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>L2O_To_Stage__c</fullName>
        <label>To Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>L2O_Opportunity_Stage</valueSetName>
        </valueSet>
    </fields>
    <label>Stage Metric</label>
    <nameField>
        <displayFormat>SM-{00000}</displayFormat>
        <label>Stage Metric Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage Metrics</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <description>This record type used for Stage Metrics adaptation for Agreements</description>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/L2O_Opportunity_Stage.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Discovery</fullName>
    </customValue>
    <customValue>
        <fullName>Proposal</fullName>
    </customValue>
    <customValue>
        <fullName>Review/Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Contracting</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Won</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Lost</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Author Contract</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Language Approval</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Language Approved</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Other Party Signatures</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Internal Review</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Other Party Review</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Returned to Requestor</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - New</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Request</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Request Approval</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Submitted Request</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Contract Ops Review</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Approved Request</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Cancelled Request</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - In Amendment</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Activated</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - In Effect</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Being Activated</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Being Amended</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Being Renewed</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - In Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Superseded</fullName>
    </customValue>
    <customValue>
        <fullName>In Authoring - Being Terminated</fullName>
    </customValue>
    <masterLabel>Opportunity Stage</masterLabel>
</GlobalValueSet>

classes/L2O_StageMetricTriggerHelperService.cls
/**
* Company : Teladoc.
* @description : L2O_StageMetricTriggerHelperService will be executed from the L2O_StageMetricTriggerHandler and will update Business Hours field on Stage Metric
* *****************************************************************************************************************************************
* History : 
* @date 05/23/2024
* @author Sachin Pawar
*/
public without sharing class L2O_StageMetricTriggerHelperService {
    public void setBusinessHours() {
        List<L2O_Stage_Metric__c> listStageMetrics = Trigger.new;
        //Selecting default business hours (BH) record Business_Hours
        BusinessHours defaultBH = [SELECT Id FROM BusinessHours WHERE IsDefault = true Limit 1];
        //Making sure BH record exists
        if(defaultBH != NULL && listStageMetrics!=null){
            for(L2O_Stage_Metric__c stageObj : listStageMetrics ){
                String RecordTypeId = Schema.SObjectType.L2O_Stage_Metric__c.getRecordTypeInfosByName().get('Agreement').getRecordTypeId();
                //Making sure that Stage date field is populated and is updated
                if(stageObj.L2O_From_Stage_Date__c != NULL && stageObj.L2O_To_Stage__c != NULL && stageObj.RecordTypeId ==RecordTypeId ){
                    Datetime  toDate = (stageObj.L2O_Current_Stage_Date__c==null) ? DateTime.now() :stageObj.L2O_Current_Stage_Date__c;
                    //For BH method we assign (BH record id, start time field, end time field)
                    Decimal result = BusinessHours.diff(defaultBH.Id,  stageObj.L2O_From_Stage_Date__c,toDate );
                   //Result from the method is divided by 60*60*100 (milliseconds to be then converted into hours)
                    Decimal resultingHours = result/(60*60*1000);
                    //Populating result into our custom field & setting number of decimals
                    stageObj.Business_Hours__c = resultingHours.setScale(2); 
                }  
            }    
        }
    }
}