objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <description>Approval Status of the Quote</description>
        <inlineHelpText>Approval Status of the Quote.</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/QuoteExtControllerTest.cls
/**************************************************************************************************
* author        : Utkarsh Chaurasia
* date          : 10/03/2022
* Name          : QuoteExtControllerTest
* @description  : Test Class for QuoteExtController for enabling Quote Object Advanced Approval Process
* History       :
**************************************************************************************************/
@isTest
private class QuoteExtControllerTest {
    
    /**
     * @name  testSubmit()
     * @description To create test scenario on Submit action
     * @params  none
     */
    static testMethod void testSubmit() {
        List<Account> accountList= L2O_DataFactoryTest.createAccount(true,2);
        List<Contact> conList =  L2O_DataFactoryTest.createContact(true,accountList); 
        List<Opportunity> oppList =  L2O_DataFactoryTest.createOpportunity(true,accountList); 
        L2O_DataFactoryTest.createContactRoles(true,oppList,conList[0].id);    
        List<SBQQ__Quote__c> quoteList =  L2O_DataFactoryTest.createQuote(true,oppList);
        
        //SBQQ__Quote__c quote = new SBQQ__Quote__c();
        //insert quote;
        
        Test.startTest();
        QuoteExtController con = new QuoteExtController(new ApexPages.StandardController(quoteList[0]));
        con.onSubmit();
        SBQQ__Quote__c quote = [SELECT ApprovalStatus__c FROM SBQQ__Quote__c WHERE Id = :quoteList[0].Id LIMIT 1];
        Test.stopTest();
        
        System.assertEquals('Approved', quote.ApprovalStatus__c,'Quote is not Approved.');
    }
    
    /**
     * @name testRecall()
     * @description To create test scenario in Recall action
     * @params  none
     */
    static testMethod void testRecall() {
        List<Account> accountList= L2O_DataFactoryTest.createAccount(true,2);
        List<Contact> conList =  L2O_DataFactoryTest.createContact(true,accountList); 
        List<Opportunity> oppList =  L2O_DataFactoryTest.createOpportunity(true,accountList); 
        L2O_DataFactoryTest.createContactRoles(true,oppList,conList[0].id);    
        List<SBQQ__Quote__c> quoteList =  L2O_DataFactoryTest.createQuote(true,oppList);
        
        //SBQQ__Quote__c quote = new SBQQ__Quote__c();
        //insert quote;
        
        Test.startTest();
        QuoteExtController con = new QuoteExtController(new ApexPages.StandardController(quoteList[0]));
        con.onRecall();
        SBQQ__Quote__c quote = [SELECT ApprovalStatus__c FROM SBQQ__Quote__c WHERE Id = :quoteList[0].Id LIMIT 1];
        Test.stopTest();
        
        System.assertEquals('Recalled', quote.ApprovalStatus__c,'Quote is not successfully Recalled.');
    }
}